networks:
  mynetwork:
    driver: bridge

services:

  mysql:
    container_name: mysqlContainer
    build: 
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=andes2020
      - MYSQL_DATABASE=swiftlogix
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=andes2020
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  swiftlogix:
    container_name: swiftlogix
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      - mynetwork




